Updated
Script now supports installation from custom kanata binary location & config location

diff --git a/kanata-service b/kanata-service
--- a/kanata-service
+++ b/kanata-service
@@ -1,89 +1,89 @@
 #!/usr/bin/env bash
 
-#################### Prerequisites
-# kanata binary must be at $HOME/.local/bin/kanata
-# kanata configuration must bet at $HOME/.config/kanata/custom.kbd
-
 service_name='com.kanata'
 uid=$(id -u $(whoami))
 service_target="gui/$uid/$service_name"
 
+[[ -n $2 ]] && kanata_binary="$(realpath $2)" || echo "Incorrect/Missing binary path"
+[[ -n $3 ]] && kanata_config="$(realpath $3)" || echo "Incorrect/Missing config path"
+
 kanata_plist="$HOME/Library/LaunchAgents/$service_name.plist"
 stderr_log='/private/tmp/kanata.err.log'
-
-is_bootstrapped="$(launchctl print $service_target &> /dev/null; echo $?)"
 kanata_sudoers='/private/etc/sudoers.d/kanata'
-is_service_installed="$([[ -f $kanata_plist && -f $kanata_sudoers ]] && echo 0 || echo 11)"
+
+is_bootstrapped=$(launchctl print $service_target &> /dev/null; echo $?)
+is_service_installed=$([[ -f $kanata_plist && -f $kanata_sudoers ]] &> /dev/null; echo $?)
+
+function clear-logs {
+  [[ -f $stderr_log ]] && rm -f $stderr_log
+}
 
 function install {
   if [[ is_service_installed -eq 0 ]] then
     echo "Kanata service is already installed."
   else
-    sudo cat ./$service_name.plist | sed "s~{HOME}~$HOME~g" 1> $kanata_plist
-    sed "s~{HOME}~$HOME/.local/bin/kanata~g" <<< "$(whoami) ALL=(root) NOPASSWD: $HOME/.local/bin/kanata --cfg $HOME/.config/kanata/custom.kbd" 1>  ./kanata
-    sudo chown root:wheel ./kanata
-    sudo chmod 600 ./kanata
-    sudo cp -p ./kanata $kanata_sudoers
-    rm -f ./kanata
+    # com.kanata.plist launchd config
+    cat ./$service_name.plist | sed "s~{kanata_binary}~$kanata_binary~g" | sed "s~{kanata_config}~$kanata_config~g" 1> ./com.kanata.plist.tmp
+    sudo chmod 644 $kanata_plist
+    sudo cp -vp ./com.kanata.plist.tmp $kanata_plist && rm -f ./com.kanata.plist.tmp
+
+    # sudoers.d kanata
+    sed "s~{kanata_binary}~$kanata_binary~g" <<< "$(whoami) ALL=(root) NOPASSWD: $kanata_binary --cfg $kanata_config" 1>  ./kanata.tmp
+    sudo chown root:wheel ./kanata.tmp
+    sudo chmod 600 ./kanata.tmp
+    sudo cp -vp ./kanata.tmp $kanata_sudoers && rm -rf ./kanata.tmp
+
     echo "Installed service."
   fi
 }
 
-function uninstall {
-  if [[ $is_service_installed -eq 0 ]] then
-    sudo rm -vf $kanata_plist
-    sudo rm -vf $kanata_sudoers
-    echo "Uninstalled service"
-  else
-    echo "Service isn't installed."
-  fi
-}
-
 function start {
-  [[ -f $stderr_log ]] && rm -f $stderr_log
-  if [[ $is_service_installed -eq 0 ]] then
+  if [[ $is_service_installed -ne 0 ]] then
+    echo "Service isn't installed."
+  else
+    clear-logs
     if [[ is_bootstrapped -eq 0 ]] then
       launchctl kickstart $service_target
     else
       launchctl enable $service_target
       launchctl bootstrap gui/$uid $kanata_plist && echo "Kanata service starting..."
-      sleep 5
+      sleep 2
     fi
-  else
-    echo "Service isn't installed."
   fi
 }
 
 function stop {
-  if [[ is_service_installed -eq 0 ]] then
+  if [[ is_service_installed -ne 0 ]] then
+    echo "Service isn't installed."
+  else
     if [[ is_bootstrapped -eq 0 ]] then
-      launchctl bootout gui/$uid $kanata_plist && echo "Service stopped."
+      echo "Suspending the server..."
+      launchctl bootout gui/$uid $kanata_plist
+      read -d "," -s -t 2 --
       launchctl disable $service_target
     else
       launchctl kill 9 $service_target &> /dev/null
     fi
-  else
-    echo "Service isn't installed."
   fi
 }
 
 function restart {
-  if [[ is_service_installed -eq 0 ]] then
+  if [[ is_service_installed -ne 0 ]] then
+    echo "Service isn't installed."
+  else
     if [[ is_bootstrapped -eq 0 ]] then
-      [[ -f $stderr_log ]] && rm -f $stderr_log
+      clear-logs
       launchctl kickstart -k gui/$uid/$service_name && echo "Service restarting..."
     else
       stop
       start
     fi
-  else
-    echo "Service isn't installed."
   fi
 }
 
 function debug {
   if [[ is_service_installed -eq 0 ]] then
-    [[ -f $stderr_log ]] && tail -f $stderr_log || echo "No errors"
+    [[ -f $stderr_log ]] && tail -f $stderr_log || echo "No errors reported yet."
   else
     echo "Service isn't installed."
   fi
@@ -97,9 +97,29 @@ function info {
   fi
 }
 
-if [[ -z $1 ]] then
-  echo "Available commands: install, uninstall, start, stop, restart, info, debug."
-else
-  $1
-fi
+function uninstall {
+  if [[ $is_service_installed -ne 0 ]] then
+    echo "Service isn't installed."
+  else
+    stop
+    sudo rm -vf $kanata_plist
+    sudo rm -vf $kanata_sudoers
+    echo "Uninstalled service"
+  fi
+}
 
+function help {
+  echo "Usage:
+    Installation: kanata-service install <kanata_binary> <kanata_config>
+    Other: kanata-service <command>
+Available commands:
+    1. install - installs the launchd com.kanata.plist file & and adds kanata to sudoers.d
+    2. uninstall - deletes the launchd com.kanata.plist file & removes the kanata sudoers.d
+    3. start - starts the service
+    4. stop - stops the service
+    5. restart - restarts the service
+    6. info - prints properties of the com.kanata launchd service
+    7. debug - concatenates the stderr.log to stdout"
+}
+
+[[ -z $1 ]] && help || $1 $2 $3
